application:
    build: ./docker/code
    volumes:
        - ./:/var/www/symfony
        - ./app/logs:/var/www/symfony/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
solr:
    image: solr
    ports:
        - 8983:8983
php:
    build: ./docker/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
        - solr
nginx:
    build: ./docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx
