application:
    build: ./docker/code
    volumes:
        - ./:/var/www/symfony
        - ./app/logs:/var/www/symfony/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
solr:
    image: solr
    ports:
        - 8983:8983
redis:
    image: redis
    ports:
        - 6379:6379
elasticsearch:
    image: elasticsearch
    ports:
        - 9200:9200
php:
    build: ./docker/php-fpm
    expose:
        - "9000"
    volumes_from:
        - application
    links:
        - db
        - solr
        - redis
        - elasticsearch
        - selenium
nginx:
    build: ./docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx

selenium:
    image: selenium/hub
    ports:
        - "4444:4444"
    environment:
      - GRID_TIMEOUT=10000
    extra_hosts:
     - "nginx:172.17.42.1"

chrome:
    image: selenium/node-chrome
    ports:
        - "5555:5555"
    links:
        - selenium:hub