<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Url;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByShortenUrl($urlr)
    {
        $this->findOneBy(
            ['shortenUrl' => $url]
        );
    }
}
