<?php
/**
 * This file is part of the "symfony-project" project
 *
 * Test class for @see AppBundle\Entity\AnotherClass
 *
 * File is generated by command "cosma_testing:generate:test"
 *
 * @link  https://github.com/cosma/testing-bundle
 *
 * Date: 08/01/2016
 * Time: 14:28
 *
 */

namespace AppBundle\Tests\Entity;

use \Cosma\Bundle\TestingBundle\TestCase\SolrTestCase;

class AnotherClassTest extends SolrTestCase
{
    /**
     * @see  \AppBundle\Entity\AnotherClass::firstPublicMethodAnother
     */
     public function testFirstPublicMethodAnother()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\AnotherClass::secondPublicMethodAnother
     */
     public function testSecondPublicMethodAnother()
     {
        //write your test here
     }


}
