<?php
/**
 * This file is part of the "symfony-project" project
 *
 * Test class for @see AppBundle\Entity\Book
 *
 * File is generated by command "cosma_testing:generate:test"
 *
 * @link  https://github.com/cosma/testing-bundle
 *
 * Date: 08/01/2016
 * Time: 14:28
 *
 */

namespace AppBundle\Tests\Entity;

use \Cosma\Bundle\TestingBundle\TestCase\DBTestCase;

class BookTest extends DBTestCase
{
    /**
     * @see  \AppBundle\Entity\Book::getId
     */
     public function testGetId()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::getTitle
     */
     public function testGetTitle()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::setTitle
     */
     public function testSetTitle()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::getPrice
     */
     public function testGetPrice()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::setPrice
     */
     public function testSetPrice()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::getDescription
     */
     public function testGetDescription()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\Book::setDescription
     */
     public function testSetDescription()
     {
        //write your test here
     }


}
