<?php
/**
 * This file is part of the "symfony-project" project
 *
 * Test class for @see AppBundle\Entity\CevaTrait
 *
 * File is generated by command "cosma_testing:generate:test"
 *
 * @link  https://github.com/cosma/testing-bundle
 *
 * Date: 08/01/2016
 * Time: 14:28
 *
 */

namespace AppBundle\Tests\Entity;

use \Cosma\Bundle\TestingBundle\TestCase\SeleniumTestCase;

class CevaTraitTest extends SeleniumTestCase
{
    /**
     * @see  \AppBundle\Entity\CevaTrait::firstPublicMethod
     */
     public function testFirstPublicMethod()
     {
        //write your test here
     }


    /**
     * @see  \AppBundle\Entity\CevaTrait::secondPublicMethod
     */
     public function testSecondPublicMethod()
     {
        //write your test here
     }


}
