source "https://supermarket.getchef.com"

group :solo do
    cookbook "apt"
    cookbook "apt-periodic"
    cookbook "ntp"
    cookbook "nginx"
    cookbook "php"
    cookbook "composer"
    cookbook "mysql"
    cookbook "database"

##
#       Application specific role cookbooks
##
    cookbook "default",         path: "./cookbooks/default"
    cookbook "symfony",         path: "./cookbooks/symfony"
    cookbook "app",             path: "./cookbooks/app"
    cookbook "db",              path: "./cookbooks/db"
end